window.treeds = {};
window.treeds.template = [
	'<header>',
	'<div class="header-tabs">',
		'<div class="wrap">',
			'<a class="current-tab" href="http://timhortons.com/"></a>',
		'</div>',
    '</div>',
		'<div class="shadow">',
			'<div class="wrap">',
				'<a id="logo" title="Tim Hortons" href="http://timhortons.com/"></a>',
			'</div>',
        '</div>',
	'</header>',
	'<div class="content">',
		'<div class="wrap wrap-bg">',
			'<iframe id="buyatab-frame" src="{{{src}}}" width="100%" frameborder="0" scrolling="no"></iframe>',
		'</div>',
	'</div>',
	'<footer>',
		'<div class="wrap">',
			'<div class="support center"> Customer Support: 1-888-267-0447</br> Buyatab Online Inc. All Rights Reserved </div>',
			'<div class="logos">',
				'<a class="logo buyatab" href="https://www.buyatab.com"></a>',
			'</div>',
		'</div>',
	'</footer>'
].join('\n');