window.template = [
"<div id='wrapper' class='receipt'>",
	"<header>",
		"<hgroup>",
			"<h1>{{{ Merchant.Name }}}</h1>",
			"<h2>Thank you for placing your order</h2>",
		"</hgroup>",
			
	"</header>",
							
	"<div id='message'>",
		"<p>",
			"Your order number is <span class='bold'>{{{ OrderNumber }}}</span>. It will be processed shortly and once completed a receipt will be sent to <span class='bold'>{{{ PurchaserName }}}</span> at {{{ PurchaserEmail }}}.",
		"</p>",
		// "<p>",
		// 	"",
		// "</p>",
		"<h2>ORDER SUMMARY</h2>",
		// "<div class='action'>",
			"<ul id='items-detail'>",
			"{{#each Items}}",
				"<li>",
					"<div class='card-img'>",
						"{{#if CardImg }}",
							"<img src='{{{ CardImg }}}' />",
						"{{else}}",
							"<img src='' />",
						"{{/if}}",
					"</div>",

					"<div class='first-column'>",
						// "<div>",
						// 	"<span class='bold'>Ref Id: </span> #{{{ Id }}} ",
						// "</div>",

						"<div>",
							"<span class='bold'>To: </span> {{{ To }}} ",
						"</div>",
						"{{#if Amount}}",
						"<div>",
							"<span class='bold'>Amount: </span> {{{ ../../Merchant.CurrencySign }}} {{{ Amount }}}",
						"</div>",
						"{{/if}}",
					"</div>",
					"<div class='second-column'>",
						"<div>",
							"<span class='bold'>Delivery type: </span> {{{ Shipment.DeliveryType }}} ",
						"</div>",
						"{{#if DeliveryDate }}",
						"<div>",
							"<span class='bold'>Purchase date: </span> {{{ Date }}}",
						"</div>",
						"{{/if}}",

						// "{{#if Shipment }}",
						"<div>",
							"<span class='bold'>Deliver to: </span> {{{ Shipment.Name }}} ",
						"</div>",
						"<div>",
							"<span class='bold'>Address: </span> {{{ Shipment.Address }}} ",
						"</div>",
						// "{{/if}}",

					"</div>",
					// "<div class='third-column'>",
						

					// "</div>",
				"</li>",
			"{{/each}}",

		"</ul>",
		// "</div>",
		
	"</div>",

	"<footer>",
		"<div id='sub-footer'>",
			"<p>",
				"If you have any questions or require further assistance, please email us at {{{ Merchant.SupportEmail }}} or call us at {{{ Merchant.SupportPhone }}}.",
			"</p>",
		"</div>",
		
		"<div class='pages-nav'>",
			"<a href='javascript:window.print()' class='button continue-button no-icon'>",
				"<span>Print</span>",
			"</a>",
		"</div>",
	"</footer>",
"</div>",
].join("\n");