window.template = [
"<div id='wrapper' class='receipt'>",
	"<header>",
		"<hgroup>",
			"<h1>{{{ Merchant.Name }}}</h1>",
			"<h2>Merci d'avoir acheté une carte-cadeau!</h2>",
		"</hgroup>",
			
	"</header>",
							
	"<div id='message'>",
		"<p>",
			"Votre numéro de commande est <span class='bold'>{{{ OrderNumber }}}</span>. Votre transaction est en cours de traitement par notre système, et quand elle sera complétée un reçu sera envoyé à <span class='bold'>{{{ PurchaserName }}}</span> {{{ PurchaserEmail }}}.  ",
		"</p>",
		"<h2>ARTICLES</h2>",

		"<ul id='items-detail'>",
			"{{#each Items}}",
				"<li>",
					"<div class='card-img'>",
						"{{#if CardImg }}",
							"<img src='{{{ CardImg }}}' />",
						"{{else}}",
							"<img src='' />",
						"{{/if}}",
					"</div>",

					"<div class='first-column'>",
						"<div>",
							"<span class='bold'>À: </span> {{{ To }}} ",
						"</div>",
						"{{#if Amount}}",
						"<div>",
							"<span class='bold'>Montant: </span>{{{ Amount }}} {{{ ../../Merchant.CurrencySign }}} ",
						"</div>",
						"{{/if}}",
					"</div>",
					"<div class='second-column'>",
						"<div>",
							"<span class='bold'>Type d'envoi: </span> {{{ Shipment.DeliveryType }}} ",
						"</div>",
						// "{{#if DeliveryDate }}",
						// "<div>",
						// 	"<span class='bold'>Date d'achat: </span> {{{ Date }}}",
						// "</div>",
						// "{{/if}}",

						// "{{#if Shipment }}",
						"<div>",
							"<span class='bold'>Envoi à: </span> {{{ Shipment.Name }}} ",
						"</div>",
						"<div>",
							"<span class='bold'>Adresse: </span> {{{ Shipment.Address }}} ",
						"</div>",
						// "{{/if}}",

					"</div>",
					// "<div class='third-column'>",
						

					// "</div>",
				"</li>",
			"{{/each}}",


		"</ul>",
		
	"</div>",

	"<footer>",
		"<div id='sub-footer'>",
			"<p>",
				"Si vous avez des questions ou si  vous avez besoin d'aide, veuillez envoyer un courriel à {{{ Merchant.SupportEmail }}} ou appelez-nous au {{{ Merchant.SupportPhone }}}.",
			"</p>",
		"</div>",
		
		"<div class='pages-nav'>",
			"<a href='javascript:window.print()' class='button continue-button no-icon'>",
				"<span>Imprimer</span>",
			"</a>",
		"</div>",
	"</footer>",
"</div>"].join("\n");